### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by abidal3** [darshanparajuli/SimpleSystemMonitorApp#4]
CPU info: 2 cores, 4 CPUs

Error:
java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
at com.dp.sysmonitor.app.monitors.cpu.CPUMonitor.g(SourceFile:438)
at com.dp.sysmonitor.app.monitors.cpu.CPUMonitor.b(SourceFile:447)
at com.dp.sysmonitor.app.monitors.cpu.CPUMonitor.C(SourceFile:426)
at com.dp.sysmonitor.app.monitors.cpu.CPUMonitor.f(SourceFile:254)
at com.dp.sysmonitor.app.monitors.a.a.o(SourceFile:95)
at com.dp.sysmonitor.app.monitors.e.a.g(SourceFile:111)
at com.dp.sysmonitor.app.monitors.e.a.a(SourceFile:11)
at com.dp.sysmonitor.app.monitors.e.a$1.run(SourceFile:35)
at java.lang.Thread.run(Thread.java:818)

**Comment by darshanparajuli** [comment]
Does it crash consistently or every once in a while?

**Comment by abidal3** [comment]
consistently
main window isn't open

**Comment by darshanparajuli** [comment]
Thanks, that's a good hint as to where in code it's messing up. I'll look into it.

**Comment by darshanparajuli** [comment]
Could you please install the following dev build and let me know if it still crashes? Thanks!

[app-release.apk.zip](https://github.com/darshanparajuli/SimpleSystemMonitorApp/files/2122065/app-release.apk.zip)

**Comment by abidal3** [comment]
java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
	at com.dp.sysmonitor.app.monitors.cpu.CPUMonitor.g(SourceFile:432)
	at com.dp.sysmonitor.app.monitors.cpu.CPUMonitor.b(SourceFile:441)
	at com.dp.sysmonitor.app.monitors.cpu.CPUMonitor.D(SourceFile:420)
	at com.dp.sysmonitor.app.monitors.cpu.CPUMonitor.f(SourceFile:248)
	at com.dp.sysmonitor.app.monitors.b.a.p(SourceFile:105)
	at com.dp.sysmonitor.app.monitors.f.a.g(SourceFile:112)
	at com.dp.sysmonitor.app.monitors.f.a.a(SourceFile:11)
	at com.dp.sysmonitor.app.monitors.f.a$1.run(SourceFile:35)
	at java.lang.Thread.run(Thread.java:818)

**Comment by darshanparajuli** [comment]
[app-release.apk.zip](https://github.com/darshanparajuli/SimpleSystemMonitorApp/files/2129722/app-release.apk.zip)

Could you try this build? 

Also, can you post the output of following commands?
```
adb shell cat /sys/devices/system/cpu/online
adb shell cat /sys/devices/system/cpu/possible
adb shell cat /sys/devices/system/cpu/offline
```
Thank you!

**Comment by abidal3** [comment]
There was another UI bug:

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
	at com.dp.sysmonitor.app.a.h.a.a(SourceFile:167)
	at com.dp.sysmonitor.app.a.h.a.a(SourceFile:86)
	at android.support.v4.app.j.b(SourceFile:2346)
	at android.support.v4.app.p.a(SourceFile:1428)
	at android.support.v4.app.p.e(SourceFile:1759)
	at android.support.v4.app.p.a(SourceFile:1827)
	at android.support.v4.app.d.f(SourceFile:797)
	at android.support.v4.app.p.b(SourceFile:2596)
	at android.support.v4.app.p.a(SourceFile:2383)
	at android.support.v4.app.p.b(SourceFile:2338)
	at android.support.v4.app.p.b(SourceFile:2215)
	at android.support.v4.app.d.e(SourceFile:649)
	at android.support.v4.app.s.b(SourceFile:145)
	at android.support.v4.view.ViewPager.a(SourceFile:1238)
	at android.support.v4.view.ViewPager.d(SourceFile:1086)
	at android.support.v4.view.ViewPager.onMeasure(SourceFile:1616)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
	at android.view.View.measure(View.java:18794)
	at android.support.v4.widget.DrawerLayout.onMeasure(SourceFile:1059)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(SourceFile:141)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2094)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6007)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5415)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)

**Comment by abidal3** [comment]
$ cat /sys/devices/system/cpu/online
0-3
$ cat /sys/devices/system/cpu/possible
0-7
$ cat /sys/devices/system/cpu/offline
4-7

**Comment by darshanparajuli** [comment]
Thanks! Here's a new build where I have changed the way cpu core count is fetched. Please let me know if it works.

[app-release.apk.zip](https://github.com/darshanparajuli/SimpleSystemMonitorApp/files/2144310/app-release.apk.zip)

**Comment by abidal3** [comment]
java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
    at com.dp.sysmonitor.app.monitors.cpu.CPUMonitor.g(SourceFile:432)
    at com.dp.sysmonitor.app.monitors.cpu.CPUMonitor.b(SourceFile:441)
    at com.dp.sysmonitor.app.monitors.cpu.CPUMonitor.E(SourceFile:420)
    at com.dp.sysmonitor.app.monitors.cpu.CPUMonitor.f(SourceFile:248)
    at com.dp.sysmonitor.app.monitors.b.a.p(SourceFile:105)
    at com.dp.sysmonitor.app.monitors.f.a.g(SourceFile:112)
    at com.dp.sysmonitor.app.monitors.f.a.a(SourceFile:11)
    at com.dp.sysmonitor.app.monitors.f.a$1.run(SourceFile:35)
    at java.lang.Thread.run(Thread.java:818)

**Comment by abidal3** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
    at com.dp.sysmonitor.app.a.h.a.a(SourceFile:167)
    at com.dp.sysmonitor.app.a.h.a.a(SourceFile:86)
    at android.support.v4.app.j.b(SourceFile:2346)
    at android.support.v4.app.p.a(SourceFile:1428)
    at android.support.v4.app.p.e(SourceFile:1759)
    at android.support.v4.app.p.a(SourceFile:1827)
    at android.support.v4.app.d.f(SourceFile:797)
    at android.support.v4.app.p.b(SourceFile:2596)
    at android.support.v4.app.p.a(SourceFile:2383)
    at android.support.v4.app.p.b(SourceFile:2338)
    at android.support.v4.app.p.b(SourceFile:2215)
    at android.support.v4.app.d.e(SourceFile:649)
    at android.support.v4.app.s.b(SourceFile:145)
    at android.support.v4.view.ViewPager.a(SourceFile:1238)
    at android.support.v4.view.ViewPager.d(SourceFile:1086)
    at android.support.v4.view.ViewPager.onMeasure(SourceFile:1616)
    at android.view.View.measure(View.java:18794)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:18794)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
    at android.view.View.measure(View.java:18794)
    at android.support.v4.widget.DrawerLayout.onMeasure(SourceFile:1059)
    at android.view.View.measure(View.java:18794)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.support.v7.widget.ContentFrameLayout.onMeasure(SourceFile:141)
    at android.view.View.measure(View.java:18794)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:18794)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:18794)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
    at android.view.View.measure(View.java:18794)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
    at android.view.View.measure(View.java:18794)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2094)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6007)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
    at android.view.Choreographer.doFrame(Choreographer.java:606)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5415)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)

**Comment by darshanparajuli** [comment]
What version of android is on the device? Seems like it's failing to figure out the correct number of cores which seems to be 8.

**Comment by abidal3** [comment]
6.0.1
For some reason the apk changed but line numbers remained the same.
You have obscure method names and from the outside it's difficult to understand what causes errors.
Maybe you should add try-catch block.
Although it seems the problem in program logic.
AIDA64 and CPU-Z works fine.

**Comment by DavidETomlin** [comment]
I have  motion system sensor
